### ISSUE TITLE
最新LEDE缺少libpolarssl

### ISSUE THREAD

**Issue by yuan2pro** [AlexZhuo/openwrt-shadowsocksr#2]
WARNING: No feed for package 'libpolarssl' found, maybe it's already part of the standard packages?

**Comment by AlexZhuo** [comment]
WARNING不会终止编译过程，你编译完之后能否运行？

**Comment by yuan2pro** [comment]
我加入了libpolarssl也不能成功编译

**Comment by AlexZhuo** [comment]
git clone https://github.com/AlexZhuo/openwrt-feeds.git package/feeds
