### ISSUE TITLE
在Openwrt 15.05.1下编译提示出错

### ISSUE THREAD

**Issue by lersh** [AlexZhuo/openwrt-shadowsocksr#3]
checking whether the C compiler works... no
configure: error: in `/home/selphy/Develop/OpenWrt-SDK-15.05.1-ramips-mt7621_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mipsel_1004kc+dsp_uClibc-0.9.33.2/pcre-8.40':
configure: error: C compiler cannot create executables
See `config.log' for more details
Makefile:78: recipe for target '/home/selphy/Develop/OpenWrt-SDK-15.05.1-ramips-mt7621_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mipsel_1004kc+dsp_uClibc-0.9.33.2/pcre-8.40/.configured_yynnn' failed
make[2]: *** [/home/selphy/Develop/OpenWrt-SDK-15.05.1-ramips-mt7621_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mipsel_1004kc+dsp_uClibc-0.9.33.2/pcre-8.40/.configured_yynnn] Error 77

**Comment by AlexZhuo** [comment]
# 如果是 uClibc SDK (15.05.1 及以下)
 git clone https://github.com/aa65535/openwrt-feeds.git package/feeds
# 如果是 musl SDK (trunk 或 LEDE) 或者上面方法不行的时候
 ./scripts/feeds update base packages
 ./scripts/feeds install zlib libopenssl libpolarssl libmbedtls libpcre

**Comment by xiasonming** [comment]
确实无法编译，老是出错。期待大神能完善。我是直接在ledeV17.01源码编译的，错误提示等我再编译一次提供。

**Comment by xiasonming** [comment]
xsm@xsm:~/lede/source$ ./scripts/feeds update base packages
Updating feed 'packages' from 'https://git.lede-project.org/feed/packages.git^ed90827282851ad93294e370860320f1af428bb2' ...
Create index file './feeds/packages.index' 
xsm@xsm:~/lede/source$ ./scripts/feeds install zlib libopenssl libpolarssl libmbedtls libpcre
WARNING: No feed for package 'libpolarssl' found, maybe it's already part of the standard packages?

**Comment by xiasonming** [comment]
一直以来都在用aa65535的源码，所以“git clone https://github.com/aa65535/openwrt-feeds.git package/feeds”不存在缺少的问题。

**Comment by AlexZhuo** [comment]
缺少编译环境
sudo apt-get install ccache build-essential
