### ISSUE TITLE
在ledeV17.01源码下编译出错,期待大神能完善。

### ISSUE THREAD

**Issue by ghost** [AlexZhuo/openwrt-shadowsocksr#4]
我是直接在ledeV17.01源码编译的，错误提示如下：

configure: error: Cannot find asciidoc in PATH.
Makefile:110: recipe for target '/home/xsm/lede/source/build_dir/target-arm_cortex-a9+vfpv3_musl-1.1.16_eabi/shadowsocksR-libev-openssl/shadowsocksR-libev-2.5.6/.configured_yyyyynyyy' failed
make[3]: *** [/home/xsm/lede/source/build_dir/target-arm_cortex-a9+vfpv3_musl-1.1.16_eabi/shadowsocksR-libev-openssl/shadowsocksR-libev-2.5.6/.configured_yyyyynyyy] Error 1
make[3]: Leaving directory '/home/xsm/lede/source/package/shadowsocksr-libev'
package/Makefile:105: recipe for target 'package/shadowsocksr-libev/compile' failed
make[2]: *** [package/shadowsocksr-libev/compile] Error 2
make[2]: Leaving directory '/home/xsm/lede/source'
package/Makefile:101: recipe for target '/home/xsm/lede/source/staging_dir/target-arm_cortex-a9+vfpv3_musl-1.1.16_eabi/stamp/.package_compile' failed
make[1]: *** [/home/xsm/lede/source/staging_dir/target-arm_cortex-a9+vfpv3_musl-1.1.16_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/xsm/lede/source'
/home/xsm/lede/source/include/toplevel.mk:197: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by AlexZhuo** [comment]
这不是makefile的问题，是你linux环境缺少asciidoc
sudo apt-get install asciidoc
